### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by ndunnett** [Sobeston/zig.guide#232]
This could be skill issue but it seems there is no way to search the guide? It would be nice to be able to search by keywords to quickly find something specific in the guide. For example, I'm just trying Zig for the first time and would like to learn more about how to define dependencies but in a quick glance couldn't find anything relevant, so I was going to search "dependency".

**Comment by Sobeston** [comment]
Hi, you're correct in that there is not any search functionality, this has been a bit low priority for me for a while. [Docusaurus has some docs on this](https://docusaurus.io/docs/search#using-typesense-docsearch), but it's something that I will probably have to do as it requires some additional hosting.

**Comment by Sobeston** [comment]
Added in e01047eaaf3c9f334702751c976e516111dbed75
