### ISSUE TITLE
local variable is never mutated

### ISSUE THREAD

**Issue by shiena** [Sobeston/zig.guide#233]
Since zig 0.12.0 there are several codes that give the local variable is never mutated error.
For example

https://github.com/Sobeston/zig.guide/blob/master/website/versioned_docs/version-0.12/01-language-basics/23-optionals.md

```zig
test "orelse" {
    var a: ?f32 = null;
    var b = a orelse 0;
    try expect(b == 0);
    try expect(@TypeOf(b) == f32);
}
```

But don't worry. This can be avoided by using a code like `_ = &a;` as described by the PRs author.
https://github.com/ziglang/zig/pull/18017

```zig
test "orelse" {
    var a: ?f32 = null;
    var b = a orelse 0;
    try expect(b == 0);
    try expect(@TypeOf(b) == f32);
    _ = &a;
    _ = &b;
}
```

**Comment by Sobeston** [comment]
Fixed this one in https://github.com/Sobeston/zig.guide/commit/51f80b5fc8f25aec2a470109ee3826ce1d8281da
Thanks for the report, trying to fix the others now

**Comment by shiena** [comment]
@Sobeston 
Thanks for the correction. The following other code also causes the same compile error.

https://github.com/Sobeston/zig.guide/blob/master/website/versioned_docs/version-0.12/01-language-basics/24-comptime.md
- comptime blocks / x, y

https://github.com/Sobeston/zig.guide/blob/master/website/versioned_docs/version-0.12/01-language-basics/25-payload-captures.md
- optional-if / maybe_num
- error union if / ent_num
- switch capture / b

https://github.com/Sobeston/zig.guide/blob/master/website/versioned_docs/version-0.12/01-language-basics/28-anonymous-structs.md
- anonymous struct literal / pt

https://github.com/Sobeston/zig.guide/blob/master/website/versioned_docs/version-0.12/01-language-basics/30-vectors.md
- vector looping / sum

**Comment by Sobeston** [comment]
Thanks again for the detailed report!
Fixed in:
- ad3804d80f99448a2801d4cb641d025269a13f7f
- 2e34474beec5b25058fa7715b36e5b329c650b75
- 21c6b61f291a6f06e60a5c41a157827deef0dcff
- 6d9c323a4da9c481c4cc0176f0d8849e7058b8d5
- e82c212677b84ff8d2f3021afa2771deecece204
