### ISSUE TITLE
Are there issues with deploying the latest version of the guide, or tagging it?

### ISSUE THREAD

**Issue by JJ** [Sobeston/zig.guide#268]
I see that the code shown here

https://github.com/Sobeston/zig.guide/blob/4d7614d400275996fde76e62f9ff85a0f1770e54/website/versioned_docs/version-0.13/02-standard-library/07.random-numbers.zig#L8

does not correspond to the one that is actually deployed [on the site](https://zig.guide/standard-library/random-numbers/) (There's the same issue with the 0.14-dev).

Additionally, clicking on "edit" leads you to a [404 page](https://github.com/Sobeston/zig.guide/tree/master/website/versioned_docs/version-0.14/02-standard-library/07-random-numbers.md) (looks like the extension has been changed to mdx?)
*Update* This last thing might be a configuration problem with Docusaurus. I've [followed up with this question in SO](https://stackoverflow.com/questions/78952242/is-there-a-way-in-docusaurus-to-change-the-default-extension-in-editurl-from-m)

**Comment by Sobeston** [comment]
Hi JJ, sorry you came across this, there are no issues with deploying but it's done manually.
