### ISSUE TITLE
Installation page for Zig 0.13.0 still refers to Zig 0.12.0

### ISSUE THREAD

**Issue by ghost** [Sobeston/zig.guide#271]
In this page for installing Zig 0.13.0:

https://zig.guide/getting-started/installation

the text still refers to Zig 0.12.0, rather than Zig 0.13.0. For example, 

> Choose a build of Zig 0.12 for Linux that matches your CPU architecture. If you're unsure which architecture you're using, this can be found with:

> Extract the archive using tar, e.g.
> tar xf zig-linux-x86_64-0.12.0.tar.xz

> Add the location of your Zig binary to your path, e.g.
> echo 'export PATH="$HOME/zig-linux-x86_64-0.12.0:$PATH"' >> ~/.bashrc

> Choose a build of Zig 0.12 for Windows that matches your CPU architecture. Most Windows systems use x86_64, also known as AMD64. If you're unsure which architecture you're using, this can be found with:

> Verify your installation with zig version. The output should look like this:
> $ zig version
> 0.12.0

These instances of 0.12 or 0.12.0 should all be replaced with 0.13 or 0.13.0.

**Comment by Sobeston** [comment]
fixed
