### ISSUE TITLE
Test "naughty pointer" does not compile

### ISSUE THREAD

**Issue by ghost** [Sobeston/zig.guide#275]
I tried the "naughty pointer" test from Language / Pointers and it didn't compile (with Zig 0.13.0):
```zig
test "naughty pointer" {
    var x: u16 = 0;
    var y: *u8 = @ptrFromInt(x);
    _ = y;
}
```
For both variables it said `error: local variable is never mutated` and `note: consider using 'const'`.

So I guess instead it should now be:
```zig
test "naughty pointer" {
    const x: u16 = 0;
    const y: *u8 = @ptrFromInt(x);
    _ = y;
}
```

I would have opened a pull request, but I think the output of the test also needs updating (because now it's a different, cleaner message), and my test files wouldn't match yours so it wouldn't look good.

**Comment by suba327777** [comment]
I think this code needs to be fixed because it didn't compile either.
In variable y, `error:local variable is never muted`
```zig
test "const pointers" {
    const x: u8 = 1;
    var y = &x;
    y.* += 1;
}
```

So I think it should be modified as follows
```zig
test "const pointers" {
    const x: u8 = 1;
    const y = &x;
    y.* += 1;
}
```
