### ISSUE TITLE
formatting syntax update in 0.13 (and later, maybe?)

### ISSUE THREAD

**Issue by nilslice** [Sobeston/zig.guide#278]
https://github.com/Sobeston/zig.guide/blob/08afb411ff2056186b99085cf265593fd56861eb/website/versioned_docs/version-0.13/02-standard-library/14-formatting-specifiers.md?plain=1#L117

This fails (testing in 0.13), and should be "3.14159e0" instead. I haven't tested in other versions to see when this previously had worked (as I assume it did in previous versions). I have not tested in later versions either.

**Comment by Sobeston** [comment]
Closed in 87ca72ffcccaa344ce65d9d6407399a7bbbda6bb + 7afdb9783c40f38d7c1fd29ac9516fd36cdce059
