### ISSUE TITLE
Sponsor / Donations?

### ISSUE THREAD

**Issue by Cobertos** [Sobeston/zig.guide#92]
Would be nice to be able to monetarily fund if possible, this resource is invaluable

**Comment by Sobeston** [comment]
Hi, I'm pleased that you'd like to donate. Currently there's no route for doing this - I need to fill out some US tax forms in order to set up github sponsors first, but thanks for reminding me. I'll get back to this thread when that's complete.

**Comment by Sobeston** [comment]
https://github.com/sponsors/Sobeston
